# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3552f85c280e7726c99f9e374a4242deac19a2202fb176e3fb08cec87715cb5f78cd0b86e6ff57fed933d4f0816df2a36be59f207fab29f7c4d9423e048a401f

test:
  secret_key_base: b4aa55353cc1a05b03e74d0b26785bf1880ab7ada4452e0f0f58d9faf1ff85a93d7a6f2a3ae2b87a60dc3a5c24b092325027a2ea7e05b6a0c0ee60168e8c6c3a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
